/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector */

#ifndef _Included_eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector
#define _Included_eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector
 * Method:    start_recognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector_start_1recognition
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector
 * Method:    pause_recognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector_pause_1recognition
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector
 * Method:    stop_recognition
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector_stop_1recognition
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector
 * Method:    start_visualization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector_start_1visualization
  (JNIEnv *, jobject);

/*
 * Class:     eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector
 * Method:    stop_visualization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_asterics_component_sensor_realsensegestures_RealSenseNativeConnector_stop_1visualization
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
